import { ArrowUpRight, GitBranch, Layers3 } from "lucide-react";
import { motion } from "framer-motion";
import Container from "../components/common/Container";
import SectionHeading from "../components/ui/SectionHeading";
import ArchitecturePreview from "../components/visuals/ArchitecturePreview";

type Project = {
  name: string;
  type: string;
  problem: string;
  architecture: string;
  stack: readonly string[];
  decisions: string;
  accent: string;
};

const projects = [
  { name: "AutoOps Pro", type: "Developer platform", problem: "Operational work lived across disconnected tools, slowing incident response and routine delivery.", architecture: "Event-driven orchestration layer with role-aware workflows and observable service boundaries.", stack: ["React", "Node.js", "PostgreSQL", "Docker"], decisions: "Designed idempotent job execution and clear failure states so automation stays trustworthy under load.", accent: "from-blue-500/35" },
  { name: "Career Guardian AI", type: "AI product", problem: "Job seekers needed feedback that was specific, practical, and available at the moment of application.", architecture: "Retrieval-informed AI workflow that turns profile context into structured, actionable guidance.", stack: ["TypeScript", "Python", "OpenAI", "Supabase"], decisions: "Made evaluation outputs inspectable, so recommendations read as a useful system—not a black box.", accent: "from-sky-500/30" },
  { name: "MiniCompiler Studio", type: "Developer tooling", problem: "Compiler concepts are hard to explore when the full pipeline stays invisible to learners.", architecture: "Interactive compiler pipeline with discrete lexical, parsing, semantic, and codegen stages.", stack: ["React", "TypeScript", "AST", "Monaco"], decisions: "Kept each transformation independently observable to make complex internals easier to reason about.", accent: "from-indigo-500/30" },
  { name: "Customer Churn Intelligence", type: "Data intelligence", problem: "Retention signals were present in product data but unavailable to teams making day-to-day decisions.", architecture: "Analytics workflow connecting behavioral features, model scoring, and decision-ready reporting.", stack: ["Python", "SQL", "Power BI", "Scikit-learn"], decisions: "Balanced model performance with explainability so insights lead directly to intervention.", accent: "from-cyan-500/25" },
] as const satisfies readonly Project[];
export default function Projects() { return <section id="projects" className="py-24 sm:py-32"><Container><SectionHeading eyebrow="Selected work" title="Engineering case studies, not just interfaces." description="A selection of systems shaped around useful constraints: clarity, resilience, performance, and the people who operate them." /><div className="mt-14 divide-y divide-white/[.09] border-y border-white/[.09]">{projects.map((project, i) => <motion.article key={project.name} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-90px" }} transition={{ duration: .55, delay: i * .06 }} className="group grid gap-7 py-10 transition-colors duration-300 hover:bg-white/[.012] lg:grid-cols-[.85fr_1.35fr] lg:gap-16 lg:py-14"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-sky-300">0{i + 1} / {project.type}</p><h3 className="mt-3 text-2xl font-semibold tracking-[-.035em] text-slate-100 transition-colors duration-300 group-hover:text-white">{project.name}</h3><ArchitecturePreview accent={project.accent} label={project.name} index={i} /></div><div className="flex flex-col justify-between"><div className="grid gap-6 sm:grid-cols-2"><Detail label="Problem">{project.problem}</Detail><Detail label="Architecture">{project.architecture}</Detail><Detail label="Engineering decision" className="sm:col-span-2">{project.decisions}</Detail></div><div className="mt-9 flex flex-wrap items-center gap-x-5 gap-y-3"><div className="flex flex-wrap gap-2">{project.stack.map(s => <span key={s} className="rounded border border-white/[.09] bg-white/[.025] px-2.5 py-1 text-xs text-slate-400 transition-colors duration-200 hover:border-sky-400/30 hover:text-sky-100">{s}</span>)}</div><div className="ml-auto flex gap-3"><a aria-label={`${project.name} source`} href="#contact" className="rounded p-1 text-slate-400 transition hover:bg-white/5 hover:text-white"><GitBranch size={17}/></a><a aria-label={`${project.name} demo`} href="#contact" className="rounded p-1 text-sky-300 transition hover:bg-sky-400/10 hover:text-sky-100"><ArrowUpRight size={18}/></a></div></div></div></motion.article>)}</div></Container></section>; }
function Detail({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <div className={className}><p className="mb-2 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[.16em] text-slate-500"><Layers3 size={12} className="text-sky-400"/>{label}</p><p className="text-sm leading-6 text-slate-400">{children}</p></div>; }
